# Generated by Django 6.0.6 on 2026-06-12 08:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherence',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
