# Generated by Django 6.0.6 on 2026-07-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_doctor_doctornotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='password123', max_length=128),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='password123', max_length=128),
        ),
    ]
